### ISSUE TITLE
请教和nacos的对比,有什么特色功能

### ISSUE THREAD

**Issue by quqiangsheng** [alipay/sofa-registry#7]
### Your question

请教和nacos的对比,有什么特色功能
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARegistry version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by atellwu** [comment]
SOFARegistry 和 Nacos 最主要的不同是：Nacos 把配置管理和服务发现的功能集成在一起；SOFARegistry 专注于服务发现和服务注册能力，对于配置管理部分会有另外的配置中心产品进行独立承载职责，这样的划分形式希望职责分明，每种能力都做到最强。

**Comment by Viyond** [comment]
yep

**Comment by slieer** [comment]
> SOFARegistry 和 Nacos 最主要的不同是：Nacos 把配置管理和服务发现的功能集成在一起；SOFARegistry 专注于服务发现和服务注册能力，对于配置管理部分会有另外的配置中心产品进行独立承载职责，这样的划分形式希望职责分明，每种能力都做到最强。

这个说法不准确。nacos支持配置管理和服务发现单jvm方式部署，或两者分开进行部署的。
我一直在用nacos。
